
logging:
  level:
    ru.fakel.smile.file.hosting: DEBUG
    com.zaxxer:
      hikari: TRACE
      hikari.HikariConfig: DEBUG

app:
  amazon:
   s3:
     accessKeyId: ${S3_ACCESS_KEY_ID:minioadmin}
     secretAccessKey: ${S3_SECRET_ACCESS_KEY:minioadmin}
     serviceEndpoint: ${S3_SERVICE_ENDPOINT:http://localhost:9000}
     signerType: ${S3_SERVICE_TYPE:AWSS3V4SignerType}
     region: ${S3_REGION:us-east-1}

